apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -i1

resources:
- ../base/workflow-controller

namespace: argo

patches:
  - path: overlays/workflow-controller-configmap.yaml
  - path: overlays/workflow-controller-deployment.yaml